### PR TITLE
Migrated code to null-safety

### PR DESCRIPTION
**Pull request by TheOneWithTheBraid**
Please note: currently, there are immense issues with the map view provided by `flutter_map`. These issues are fixed in https://github.com/fleaflet/flutter_map/pull/923. You should not merge this PR until `flutter_map` published `0.13.1`.

### CODE REVIEW

**Comment by Xennis** [comment]
Dear @TheOneWithTheBraid the [dev](https://github.com/Xennis/flutter_map_location/tree/dev) branch already contains null safety. Can you please rebase your PR against that branch and see if something is missing?

I'll merge that branch soon into the master if flutter_map has published that version.

**Comment by TheOneWithTheBraid** [comment]
@Xennis If `dev` already contains null safety, I don't think it's necessary to merge this branch. I would rather propose to close this PR in favor of merging `dev` into `master` and afterwards publishing `master` to pub.dev.

**Comment by TheOneWithTheBraid** [comment]
If you don't mind, I will open a clean PR fixing the dependecy issues.

**Comment by Xennis** [comment]
Great :+1: 

Now null safety is merged into the master #66 A release will follow soon.

**Pull request closed without merging**
