### PR TITLE
Add a controller #69

### PR DESCRIPTION
**Pull request by Xennis**
- [x] Add a controller to the plugin options
- [x] Add function to unsubscribe
- [ ] Add function to subscribe
- [ ] Find a way to handle the location service status

### CODE REVIEW

**Comment by MichalNemec** [comment]
Hello, any update?

**Comment by Xennis** [comment]
It's still WIP (work in progress). The latest progress is the WIP commit from the weekend that I had pushed. It's not a simple task to adjust the code in a way it works with a controller.

**Comment by MichalNemec** [comment]
i know, thank you for heading right away to remake this. I didnt find anything better than this package, but toggeable location is a must, which could be done here. If i was really strong in dart, i could do it, but im not =)

**Comment by Xennis** [comment]
Let's do it in smaller PR instead.  #76 adds the controller and #77 moves further stuff into the controller.

**Pull request closed without merging**
