### PR TITLE
Add plugin option to set GPS accuracy

### PR DESCRIPTION
**Pull request by SeCo89**
Added the possibility to set the GPS accuracy via desiredAccuracy of the geolocator library.

### CODE REVIEW

**Review by Xennis — APPROVED** [review]
Thank you. Looks fine (apart from the failing check action because of the format).

**Comment by Xennis** [comment]
Dear @SeCo89 thanks a lot. I'm happy to merge you request once the CI passed. Currently the Flutter format check fails:

https://github.com/Xennis/flutter_map_location/pull/79/checks

Can you please either run `flutter format .` yourself and push again into the PR here? Otherwise you can also [allow changes to your pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) and I can do it.

**Comment by SeCo89** [comment]
I have checked the allow edits checkbox. Is there something else to do to grant you editing rights?

**Comment by Xennis** [comment]
@SeCo89 thanks for you help. I was able to push a commit into your fork so that the formatting is fixed.

**Pull request merged**
